<prog> ::= <expr-list>

<expr-list> ::= <expr> <expr-list>
                | eps

# <expr> ::= let <id> = <expr> in <expr>
#            | <expr> <binop> <expr>
#            | <unop> <expr>
#            | fun <arg-list> -> <expr>
#            | <const>
#            | [ <list-elems> ]
#            | ( <expr> )
#            | <expr> <expr>
#            | if <expr> then <expr> else <expr>
#            | <id>

<expr> ::= let <id> = <expr> in <expr> <expr'>
           | <unop> <expr> <expr'>
           | fun <arg-list> -> <expr> <expr'>
           | <const> <expr'>
           | [ <list-elems> ] <expr'>
           | ( <expr> ) <expr'>
           | if <expr> then <expr> else <expr> <expr'>
           | <id> <expr'>

<expr'> ::= <binop> <expr>
            | <expr>
            | eps

<binop>   ::= + | - | * | / | +. | -. | *. | /. | < | <= | > | >= | == | ~= | & | '|' | ^ | && | '||' | :: | .. | ,
<unop>    ::= - | ! | hd | tl | fst | snd
<arg-list> ::= <identifier> , <arg-list>
               | <identifier>
<const>   ::= -?[0-9]+ | -?[0-9]+.[0-9]* | " [\x20-\x7F] " | [] | ()
<id>      ::= [a-zA-Z_][0-9a-zA-Z_]+

<list-elems> ::= <expr> ; <list-elems>
                 | eps
